#include Shared/CharacterSheet

perkButtonPosition = {
	['perk1'] = {x = perkCol1, z = -0.807}, ['perk2'] = {x = perkCol2, z = -0.807}, ['perk3'] = {x = perkCol1, z = -0.731},
	['perk4'] = {x = perkCol1, z = -0.656}, ['perk5'] = {x = perkCol1, z = -0.531}, ['perk6'] = {x = perkCol1, z = -0.403},
	['perk7'] = {x = perkCol2, z = -0.404}, ['perk8'] = {x = perkCol1, z = -0.273}, ['perk9'] = {x = perkCol2, z = -0.273},
	['perk10'] = {x = perkCol1, z = -0.195}, ['perk11'] = {x = perkCol1, z = -0.120}, ['perk12'] = {x = perkCol2, z = -0.120},
	['perk13'] = {x = perkCol1, z = 0.002}, ['perk14'] = {x = perkCol1, z = 0.085}, ['perk15'] = {x = perkCol1, z = 0.193},
}
checkZ = 0.40