#include Shared/CharacterSheet

perkButtonPosition = {
	['perk1'] = {x = perkCol1, z = -0.807}, ['perk2'] = {x = perkCol1, z = -0.731}, ['perk3'] = {x = perkCol2, z = -0.731},
	['perk4'] = {x = perkCol1, z = -0.603}, ['perk5'] = {x = perkCol2, z = -0.603}, ['perk6'] = {x = perkCol1, z = -0.531},
	['perk7'] = {x = perkCol1, z = -0.456}, ['perk8'] = {x = perkCol1, z = -0.381}, ['perk9'] = {x = perkCol1, z = -0.249},
	['perk10'] = {x = perkCol1, z = -0.175}, ['perk11'] = {x = perkCol2, z = -0.175}, ['perk12'] = {x = perkCol1, z = -0.100},
	['perk13'] = {x = perkCol2, z = -0.100}, ['perk14'] = {x = perkCol1, z = -0.022}, ['perk15'] = {x = perkCol1, z = 0.123},
}
checkZ = 0.362